resources:
- application.yaml



Unable to create application: application spec for vault-csi-app is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = `kustomize build <path to cached source> failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from 'application.yaml': evalsymlink failure on '<path to cached source>/application.yaml' : lstat <path to cached source>/application.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '<path to cached source>/application.yaml' : lstat <path to cached source>/application.yaml: no such file or directory