apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-vault-csi-app
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: 'https://helm.releases.hashicorp.com'
      targetRevision: 0.28.1
      chart: vault
      helm:
        releaseName: argo-vault-csi
        values: |
          global:
            enabled: true
            tlsDisable: true
          injector:
            enabled: false

          csi:
            enabled: true

          server:
            image:
              repository: "hashicorp/vault"
              tag: "latest"
            standalone:
              enabled: false
            affinity: ""
            dataStorage:
              storageClass: standard
            ha:
              enabled: true
              replicas: 2
              raft:
                enabled: true
                setNodeId: true
                config: |
                  cluster_name = "vault-csi-integrated-storage"
                  ui = true
                  listener "tcp" {
                    tls_disable = "true"
                    address = "[::]:8200"
                    cluster_address = "[::]:8201"
                  }
                  storage "raft" {
                    path = "/vault/data"
                    retry_join {
                      leader_api_addr = "http://argo-vault-csi-0.argo-vault-csi-internal:8200"
                    }
                    retry_join {
                      leader_api_addr = "http://argo-vault-csi-1.argo-vault-csi-internal:8200"
                    }
                  }
                  disable_mlock = true
                  service_registration "kubernetes" {}
          # Vault UI
          ui:
            enabled: true
            serviceType: "ClusterIP"
            serviceNodePort: null
            externalPort: 80

    - repoURL: 'https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts'
      chart: secrets-store-csi-driver
      targetRevision: 1.4.4
      helm:
        values: |
          syncSecret:
            enabled: true
          enableSecretRotation: true
          rotationPollInterval: 2m
